### ISSUE TITLE
Truck cycling in first person causes overlaying GUI

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1051]
When you're in first person and use CTRL+] to cycle to the next vehicle, the GUI's of the two vehicles will overlap:
![guibug1](http://i.imgur.com/HnDagbw.jpg)
![guibug2](http://i.imgur.com/gYWflUm.jpg)

**Comment by only-a-ptr** [comment]
The screenshots don't show any sign of overlap, though. How exactly does the problem manifest itself?

I'm unable to test myself right now, sorry.

**Comment by AntoniD330** [comment]
@only-a-ptr Look at the gear status, just under the digital speedometer. You can see the numbers are hardly distinguishable.

**Comment by only-a-ptr** [comment]
@AntoniD330 Right. Thanks.

**Comment by Michael10055** [comment]
@AntoniD330 is right, I should've added that info to the report. Sorry for the confusion.

**Comment by only-a-ptr** [comment]
I tested with current upstream. I used "Magnum drifter" and "Agora bus S". I couldn't see any sign of HUD overlap or visual glitches.

@Michael10055 Try current upstream, and if you see something wrong, give me detailed test instructions please.

**Comment by Michael10055** [comment]
@only-a-ptr I just tested it on the current upstream, it looks like this issue is fixed. 😄

**Comment by tritonas00** [comment]
I think this issue is still valid. I spawned two vehicles, switched to first person view and then switched through vehicles using CTRL + [ ] and switched cameras again

Result two overlaying huds
![2017-06-03-222750_1366x768_scrot](https://cloud.githubusercontent.com/assets/2660424/26756492/3d4e6928-48ac-11e7-9f0d-f25c3d5ed0d9.png)

**Comment by Michael10055** [comment]
Yup, it is still valid.
