### ISSUE TITLE
Character spawn rotation

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#3226]
In recent builds, the character occasionally spawns facing the opposite direction:

![Image](https://github.com/user-attachments/assets/9e949a28-1e55-4a36-b8d2-4fd1c79f6380)

The initial spawn rotation is determined by the existence of a predefined terrain actor.

It would be great if `StartRotation` was added to the `terrn2` file format, existing maps without this would fallback to the current behavior.

**Comment by ohlidalp** [comment]
Easy to implement, you may be able to do it by following the existing terrn2 setting `[General] StartPosition`

Parsing :https://github.com/RigsOfRods/rigs-of-rods/blob/master/source%2Fmain%2Fresources%2Fterrn2_fileformat%2FTerrn2FileFormat.cpp#L80

**Comment by ohlidalp** [comment]
Resolved by https://github.com/RigsOfRods/rigs-of-rods/pull/3241

**Comment by CuriousMike56** [comment]
Unfortunately the spawn rotation bug still occurs, just now with a 20% chance instead of 50%.
