### ISSUE TITLE
race timer shows wrong time 

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#68]

**Comment by Max98** [comment]
Lol... Any picture that explain this?

**Comment by Speciesx** [comment]
Here a video http://youtu.be/b48UMJH1UvI
- after 12 second race i get lap time 206'03.00 
- reseting the vehicle increase the lap time

**Comment by Max98** [comment]
I think that the timer has been acting like that way before I did the pause menu stuffs.

**Comment by Hiradur** [comment]
I haven't done races in a long time but it looks like they are not working on Linux, checkpoints don't appear. Do I have to enable them? I can't remember. :P

**Comment by Max98** [comment]
They should be there by default, check angelscript's log if they don't show up.

**Comment by Max98** [comment]
Fixed.

**Comment by Speciesx** [comment]
- reseting the vehicle increase the lap time
this bug is not fixed.

**Comment by Max98** [comment]
That bug exists from 0.38, so it will get it own fix later.
